
export default new Map([
["src/content/blog/seo-for-space-orgs-2026.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fseo-for-space-orgs-2026.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/assets/portraits.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fassets%2Fportraits.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/assets/social-cards.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fassets%2Fsocial-cards.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/components/buttons-and-links.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fcomponents%2Fbuttons-and-links.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/components/cards.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fcomponents%2Fcards.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/components/images-and-captions.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fcomponents%2Fimages-and-captions.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/foundations/brand-architecture.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Ffoundations%2Fbrand-architecture.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/foundations/brand-overview.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Ffoundations%2Fbrand-overview.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/foundations/principles.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Ffoundations%2Fprinciples.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/governance/asset-approval.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fgovernance%2Fasset-approval.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/governance/licensing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fgovernance%2Flicensing.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/identity/colour.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fidentity%2Fcolour.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/identity/imagery.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fidentity%2Fimagery.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/identity/logo.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fidentity%2Flogo.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/identity/typography.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fidentity%2Ftypography.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/sites/overview.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fsites%2Foverview.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/tokens/colour.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Ftokens%2Fcolour.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/tokens/spacing.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Ftokens%2Fspacing.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/tokens/typography.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Ftokens%2Ftypography.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/voice/science-communication.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fvoice%2Fscience-communication.mdx&astroContentModuleFlag=true")],
["src/content/brand/docs/voice/voice-and-tone.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fbrand%2Fdocs%2Fvoice%2Fvoice-and-tone.mdx&astroContentModuleFlag=true")]]);
		