minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - astro@7.3.7
  - rolldown@1.2.13
  - '@rolldown/binding-*@1.2.13'

allowBuilds:
  citation-js: false
  esbuild: true
  workerd: true
  sharp: true