import fs from 'node:fs';
import path from 'node:path';
import { aliasTarget, cssVar, distDir, formatValue, isAlias, loadAll, type Token } from './lib/tokens';

const errors: string[] = [];
const { base, dark } = loadAll(errors);
if (errors.length) {
  console.error(errors.join('\n'));
  process.exit(1);
}

const decl = (t: Token) =>
  `${cssVar(t.name)}: ${isAlias(t.raw) ? `var(${cssVar(aliasTarget(t.raw))})` : formatValue(t.raw)};`;

const block = (selector: string, tokens: Token[], indent = '') =>
  `${indent}${selector} {\n${tokens.map((t) => `${indent}  ${decl(t)}`).join('\n')}\n${indent}}`;

const header = '/* Generated by scripts/build-token-css.ts. Do not edit. */\n';

const tokensCss = [
  header,
  block(':root', base),
  '',
  '@media (prefers-color-scheme: dark) {',
  block(':root:not([data-theme="light"])', dark, '  '),
  '}',
  '',
  block(':root[data-theme="dark"]', dark),
  '',
].join('\n');

const sites = base.filter((t) => t.name.startsWith('color.site.'));
const themesCss =
  header +
  '\n' +
  sites
    .map((t) => {
      const id = t.path[t.path.length - 1];
      return `[data-site="${id}"] {\n  --color-accent-site: var(${cssVar(t.name)});\n}`;
    })
    .join('\n\n') +
  '\n';

fs.mkdirSync(distDir, { recursive: true });
// Scoped to the .bd wrapper so brand tokens cannot leak into the rest of the site.
const scoped = (tokensCss + '\n' + themesCss).replaceAll(':root', '.bd').replaceAll('[data-site=', '.bd[data-site=');
fs.writeFileSync(path.join(distDir, '..', 'styles', 'tokens.css'), '/* Generated by scripts/brand (npm run brand:tokens). Scoped to .bd. */\n' + scoped);
console.log(`tokens.css: ${base.length} tokens, ${dark.length} dark overrides. themes.css: ${sites.length} site accents.`);
